### ISSUE TITLE
Loading more items in mode: reverse 

### ISSUE THREAD

**Issue by morajabi** [inokawa/virtua#162]
**Is your feature request related to a problem? Please describe.**
I use virtua in a chat message list and when scroll hits the top we load more messages. But we lose scroll state and either jump to offset: 0 at top or far bottom.

**Describe the solution you'd like**
It should have a way to pin scroll to top most item in the viewport so user doesn't feel any jumps.

**Describe alternatives you've considered**
Using a useLayoutEffect to scroll to that item manually works but is janky and not smooth.

**Additional context**
In general, mode: reverse scroll positioning can be improved, eg. to load at the bottom initially and not top, keep at bottom when item sizes change, etc. We can implement most of these given flexible APIs. What's important is user shouldn't feel any frames in a _between state_ that preserves like a jump.

**Comment by inokawa** [comment]
Hi, I'm developing a prop in #147 for similar purpose, which will switch keeping position from bottom not top when items are shifted/unshifted.

It's almost working but the api isn't finalized yet. And it still cause jump in edge case.

As you pointed out, positioning can be improved in reverse scrolling but I'm bit wary to implement them because each people may have different use cases.

https://github.com/inokawa/virtua/assets/48897392/36d76077-55df-4930-957d-5b5c84617e35

**Comment by morajabi** [comment]
This is fantastic. My issues that I can't workaround are 2:
1. bi-directional loading more (which this PR solves)
2. jump when item size changes (imagine in Slack when you add a reaction to a message, it should still stay at bottom, but my scrollToBottom that uses scrollToOffset is one frame late for some reason)

**Comment by inokawa** [comment]
If you just want to stay to bottom when items added, scrollToIndex with end align may work:

```tsx
const ref = useRef<VListHandle>(null).
useEffect(() => {
  ref?.current.scrollToIndex(elements.length - 1, "end");
}, [elements.length]

return <VList ref={ref}>{elements}</VList>
```

https://github.com/inokawa/virtua/blob/691183aead020bd0a0345da745f9d1996eb3d9ef/stories/advanced/Chat.stories.tsx#L69-L72

Sticking to bottom automatically might be better, and it is actually implemented as jump handling for scrollToIndex , but it's not exposed as props yet.

**Comment by morajabi** [comment]
@inokawa we are doing a release later today with virtua for our message list (for https://noor.to) is there anyway I can make a PR or for you to expose this as an option? we're loving virtua so far.

**Comment by inokawa** [comment]
That's sounds nice!

The stick to bottom during imperative scrolling logic is here. PRs are welcome but I doubt it would not work for other purpose as it is, because it's designed to work with imperative scrolling and the jump compensation in this lib is very timing dependent.

https://github.com/inokawa/virtua/blob/691183aead020bd0a0345da745f9d1996eb3d9ef/src/core/store.ts#L213-L227

**Comment by inokawa** [comment]
Finally, #147  is released as `shift` prop in `0.8.0`.
A known issue will be tracked in #163 .

**Comment by Bessonov** [comment]
Hey @inokawa , great! Is there a way to track "Reverse scroll in iOS Safari"?

**Comment by inokawa** [comment]
Hi @Bessonov , the issue in iOS Safari will be processed in #43 .

**Comment by inokawa** [comment]
For a note, I changed the compensation logic described in https://github.com/inokawa/virtua/issues/162#issuecomment-1682183707 to work in more situations in `0.13.0`.
I close this issue because of inactivity, but feel free to reopen it if you have any problems.
