### ISSUE TITLE
Type issue while using Nuxt 3, Typsecript and Vue 3

### ISSUE THREAD

**Issue by jesspinklet** [inokawa/virtua#366]
**Describe the bug**
I'm using Nuxt 3 and Vue 3 

![image](https://github.com/inokawa/virtua/assets/77070946/cb2dd926-80e7-47fb-9ccc-8e849862642a)

 While I'm importing the components in viruta 0.23.3 it throws error at just in vs-code and not in production.

**Comment by inokawa** [comment]
Could you show me your tsconfig?
Set `moduleResolution: "bundler"` to your config may solve the problem for now.

**Comment by jesspinklet** [comment]
> Could you show me your tsconfig? Set `moduleResolution: "bundler"` to your config may solve the problem for now.

```
{
	// https://nuxt.com/docs/guide/concepts/typescript
	"extends": "./.nuxt/tsconfig.json",
	"compilerOptions": {
		"types": [
		  "@nuxtjs/i18n",
		]
	  }
}
```
Which can be customized by nuxt.config.ts.
And inside nuxt config I have this option for bundler resolution.
```
  future: {
    typescriptBundlerResolution: false
  },
```

for further information to the latest Nuxt blog explains the [Bundler module resolution](https://nuxt.com/blog/v3-10#bundler-module-resolution)

**Comment by inokawa** [comment]
Thanks. `typescriptBundlerResolution: true` may solve the problem because Vue entry point of virtua is using exports of package.json, which can't be handled in TypeScript without `moduleResolution: bundler` or `moduleResolution: nodenext`.

We may implement fallback for legacy TypeScript if it's important for Vue ecosystem.
