### ISSUE TITLE
Cannot calculate scrollTop in VUE IOS

### ISSUE THREAD

**Issue by leejaeho1809** [inokawa/virtua#403]
**Describe the bug**
When I call up past chats using VList or Virtualizer and scroll up, the scrollTop appears to be 0 even though there are more actual elements, maybe because the IOS cannot calculate the scrollTop. And then, when the touch is stopped, the scrollTop is calculated again and the scrollTop is changed. This phenomenon only occurs on IOS Mobile and does not appear on AOS.
I think safeTop affects the calculation of scrollTop in IOS.

**Expected behavior**
Data with index number 1 should be shown when scrollTop is 0.

**Platform:**

- OS: iOS
- Browser: Safari
- Version of this package: 0.28.0
- Version of framework: vue 3.2.41

**Comment by inokawa** [comment]
Unfortunatelly, I think it's almost impossible to solve the problem because of limitation of iOS Safari.

iOS Safari prohibits updating scrollTop during momentum scrolling, so we have to shift position of items, that will sometimes exceed the scrollTop 0. If we don't shift items, we will see glitch while reverse scrolling.
