### ISSUE TITLE
`scrollToIndex` doesn't go to specified index.

### ISSUE THREAD

**Issue by jad-eljerdy** [inokawa/virtua#510]
**Describe the bug**
`scrollIndex` fails to go to specific index, instead stops somewhere before.

**To Reproduce**

* Go to https://inokawa.github.io/virtua/?path=/story/comparisons--one-million
* Keep the default settings (comparison with `react-virtualized`)
* Set the index input to 500000
* Press scroll
* `react-virtualized` goes to 500,000, `virtua` goes to 328,960 (See screenshot)

<img width="563" alt="image" src="https://github.com/user-attachments/assets/86c8d8e1-1bda-41a7-bfc5-96f55646c00a">

**Expected behavior**
`scrollIndex` should always scroll to the specified index.

**Platform:**
- OS: MacOS
- Browser: Chrome
- Version of this package: 0.34.2
- Version of framework: react

**Additional context**
Am I missing anything ?

**Comment by inokawa** [comment]
It's current expected behavior.

Virtualization libraries except react-virtualized can't render 1 million rows, which is mentioned in the comparison section of README as "Display exceeding browser's max element size limit".
https://github.com/inokawa/virtua?tab=readme-ov-file#comparison

The issue will be addressed in #32 .
