### ISSUE TITLE
Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by toniengelhardt** [inokawa/virtua#549]
**Describe the bug**
When I upgrade from `0.36.3` to `0.37.2` I get the following error:

<img width="1512" alt="Screenshot 2024-11-17 at 18 03 45" src="https://github.com/user-attachments/assets/287bb8fa-7814-478a-8e37-4e567c60cb3f">

There was a breaking change in `0.37`, but it seems unrelated?

**To Reproduce**
My setup is as follows. I have this wrapper to create virtual lists:

```ts
<script setup lang="ts" generic="T">
import { VList } from 'virtua/vue'

defineProps<{
  items: T[]
}>()

defineSlots<{
  default: (props: T) => any
}>()
</script>

<template>
  <VList
    v-slot="{ item }"
    :data="items"
    h-full
  >
    <slot v-bind="item" />
  </VList>
</template>
```

and use it like:

```ts
<div>
  <AppVirtualList
    :items="outputs"
    #default="output"
    class="custom-scrollbar"
    p-2 pb-0
  >
    <OutputListItem
        :key="output.id"
        :item="item"
    />
  </AppVirtualList>
</div>
```

If I wrap both `OutputListItem` and `VList` in a div, the error goes away, but nothing is rendered...

**Expected behavior**
Do I set it up incorrectly or is this a bug introduced in `0.37.0`?

**Platform:**

- OS: MacOS
- Browser: Chrome
- Version of this package: 0.37.2
- Version of framework: vue@3.5.12

Thanks for this amazing lib!

**Comment by paolodelfino** [comment]
Maybe the element you're trying to get and feed into the observer is not in the viewport or near the edges and therefore not in the dom.

**Comment by inokawa** [comment]
Hmm...unexpected. Does it happen with `0.37.0` and `0.37.1`?

**Comment by wkl007** [comment]
I have the same problem.

**Comment by inokawa** [comment]
Oh, `0.37.0` and `0.37.1` are not safe...

**Comment by inokawa** [comment]
Could you try `0.37.3`?

**Comment by toniengelhardt** [comment]
> Could you try `0.37.3`?

Works! Thanks a lot for the quick fix 🙏🏽

**Comment by marioparaschiv** [comment]
@inokawa Hey, this is still happening. I think a simple check would fix this.

In: https://github.com/inokawa/virtua/blob/main/src/core/resizer.ts#L21

```ts
if (!(element instanceof Element)) return;
```

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@inokawa I can also attest that this is an issue on the current version (0.42.3), although it seems to be caused by some race condition where rapid mounting and unmounting of the parent component is involved. It's been hard to isolate, but it's 100% there under the right conditions. There should be a strategy to bail entirely if the DOM element is missing.

@marioparaschiv The problem is that if you simply put that check in there, the program will continue to move forward as if the element exists, and will try to do things like adding event listeners, which will fail lead to failures in other places in the code. Curious if you've found a viable workaround.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@inokawa Please take a look at this potential fix: https://github.com/inokawa/virtua/pull/733
